services:
  postgres:
    image: postgres:16-alpine
    container_name: shezhire-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shezhire
      POSTGRES_USER: shezhire
      POSTGRES_PASSWORD: shezhire
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shezhire"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - atatek_network

  redis:
    image: redis:7-alpine
    container_name: shezhire-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - atatek_network

  adminer:
    image: adminer:4.8.1
    container_name: shezhire-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - atatek_network

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/app/public/uploads
    networks:
      - atatek_network
    restart: unless-stopped

  api:
    image: ghcr.io/karl4th/fastapi-atatek-backend:latest
    container_name: shezhire-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
    networks:
      - atatek_network

  web:
    image: ghcr.io/karl4th/nextjs-atatek-frontend:latest
    container_name: shezhire-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    restart: unless-stopped
    networks:
      - atatek_network

volumes:
  pg_data:

networks:
  atatek_network:
    driver: bridge
