version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: shezhire-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shezhire
      POSTGRES_USER: shezhire
      POSTGRES_PASSWORD: shezhire
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shezhire"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - atatek_network

  redis:
    image: redis:7-alpine
    container_name: shezhire-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - atatek_network

  api:
    image: ghcr.io/karl4th/fastapi-atatek-backend:latest
    container_name: shezhire-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - atatek_network

  web:
    image: ghcr.io/karl4th/nextjs-atatek-frontend:latest
    container_name: shezhire-web
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: https://api.atatek.kz
    networks:
      - atatek_network

  landing:
    image: ghcr.io/karl4th/next-js-atatek-landing:latest
    container_name: shezhire-landing
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: https://api.atatek.kz
    networks:
      - atatek_network

  adminer:
    image: adminer:4.8.1
    container_name: shezhire-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - atatek_network

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/app/public/uploads
    depends_on:
      - api
      - web
      - landing
    networks:
      - atatek_network

volumes:
  pg_data:

networks:
  atatek_network:
    driver: bridge
